/**:
  ros__parameters:
    environment_name: indoor

    linear_speed_factor: 0.5
    angular_speed_factor: 0.6

    acceleration_factor: 0.4
    deceleration_factor: 1.0

    stopping_distance_factor: 1.2
    watchdog_enabled: true

    timeout_seconds: 2.0