robot_info:
  ros__parameters:
    environment_name: testing

    linear_speed_factor: 1.2
    angular_speed_factor: 1.2

    acceleration_factor: 1.2

    stopping_distance_factor: 1.0
    deceleration_factor: 1.0
    watchdog_enabled: true

    timeout_seconds: 2.0